#!/bin/bash
# Calls ChatGPT with the issue body as a prompt and saves generated code to autocoder-bot/

GITHUB_TOKEN=$1
REPOSITORY=$2
ISSUE_NUMBER=$3
OPENAI_API_KEY=$4

mkdir -p autocoder-bot

# Retrieve issue body from GitHub API
ISSUE_RESPONSE=$(curl -s \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github.v3+json" \
  "https://api.github.com/repos/$REPOSITORY/issues/$ISSUE_NUMBER")

ISSUE_BODY=$(echo "$ISSUE_RESPONSE" | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(data.get('body', ''))
")

if [ -z "$ISSUE_BODY" ]; then
  echo "Error: Could not retrieve issue body."
  exit 1
fi

if [ -z "$OPENAI_API_KEY" ]; then
  echo "Warning: OPENAI_API_KEY is not set. Skipping code generation."
  echo "# Generated placeholder — set OPENAI_API_KEY secret to enable real code generation" > autocoder-bot/placeholder.txt
  exit 0
fi

# Build prompt with instructions for structured code output
INSTRUCTIONS="You are a code generator. Based on the requirements below, generate the requested code files. For each file, use the following format exactly:
### File: <filename>
\`\`\`<language>
<code>
\`\`\`

Requirements:
$ISSUE_BODY"

ESCAPED_PROMPT=$(python3 -c "import sys, json; print(json.dumps(sys.argv[1]))" "$INSTRUCTIONS")

# Send prompt to ChatGPT
OPENAI_RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d "{
    \"model\": \"gpt-3.5-turbo\",
    \"messages\": [{\"role\": \"user\", \"content\": $ESCAPED_PROMPT}],
    \"max_tokens\": 2000,
    \"temperature\": 0.2
  }")

CONTENT=$(echo "$OPENAI_RESPONSE" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if 'choices' in data:
    print(data['choices'][0]['message']['content'])
else:
    import sys; sys.stderr.write('OpenAI error: ' + str(data) + '\n')
")

if [ -z "$CONTENT" ]; then
  echo "Warning: No content returned from ChatGPT. Creating placeholder."
  echo "# No content was generated by ChatGPT" > autocoder-bot/placeholder.txt
  exit 0
fi

# Parse code blocks and save to autocoder-bot/
echo "$CONTENT" | python3 - << 'PYEOF'
import sys, re, os

content = sys.stdin.read()
os.makedirs("autocoder-bot", exist_ok=True)

pattern = re.compile(
    r'###\s+[Ff]ile:\s+(\S+)\s*\n```[^\n]*\n(.*?)```',
    re.DOTALL
)
matches = pattern.findall(content)

if not matches:
    with open("autocoder-bot/generated_code.py", "w") as f:
        f.write(content)
    print("Saved: autocoder-bot/generated_code.py")
else:
    for filename, code in matches:
        filepath = os.path.join("autocoder-bot", os.path.basename(filename))
        with open(filepath, "w") as f:
            f.write(code.strip() + "\n")
        print(f"Saved: {filepath}")
PYEOF
