name: AutoCoder Workflow
on:
  issues:
    types: [opened, labeled]

jobs:
  generate_code:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Code with ChatGPT
        id: generate_code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          chmod +x scripts/script.sh
          ./scripts/script.sh ${{ env.GITHUB_TOKEN }} ${{ env.REPOSITORY }} ${{ env.ISSUE_NUMBER }} ${{ env.OPENAI_API_KEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact/

      - name: Display Generated Code
        run: ls -R autocoder-artifact
